services:
   amqp:
      image: rabbitmq:3-management
      ports:
         - "${AMQP_INTERFACE:-127.0.0.1}:5672:5672"
         - "${AMQP_INTERFACE:-127.0.0.1}:15672:15672"

   config:
      build:
         context: ./config
         args:
            - CHAIN_TAG=${CHAIN_TAG:-latest}
      volumes:
         - "${BASEDIR}:/koinos"

   jsonrpc:
      image: koinos/koinos-jsonrpc:${JSONRPC_TAG:-latest}
      depends_on:
         - amqp
         - config
      volumes:
         - "${BASEDIR}:/koinos"
      ports:
         - "${JSONRPC_INTERFACE:-127.0.0.1}:8080:8080"
      command: --basedir=/koinos

   mempool:
      image: koinos/koinos-mempool:${MEMPOOL_TAG:-latest}
      depends_on:
         - amqp
         - config
      volumes:
         - "${BASEDIR}:/koinos"
      command: --basedir=/koinos

   block_store:
      image: koinos/koinos-block-store:${BLOCK_STORE_TAG:-latest}
      depends_on:
         - amqp
         - config
      volumes:
         - "${BASEDIR}:/koinos"
      command: --basedir=/koinos

   chain:
      image: koinos/koinos-chain:${CHAIN_TAG:-latest}
      depends_on:
         - amqp
         - block_store
         - mempool
         - config
      volumes:
         - "${BASEDIR}:/koinos"
      command: --basedir=/koinos

   p2p:
      image: koinos/koinos-p2p:${P2P_TAG:-latest}
      depends_on:
         - amqp
         - block_store
         - chain
         - config
      volumes:
         - "${BASEDIR}:/koinos"
      ports:
         - "${P2P_INTERFACE:-0.0.0.0}:8888:8888"
      command: --basedir=/koinos -G -l /ip4/0.0.0.0/tcp/8888

   block_producer:
      image: koinos/koinos-block-producer:${BLOCK_PRODUCER_TAG:-latest}
      depends_on:
         - amqp
         - mempool
         - chain
         - config
      volumes:
         - "${BASEDIR}:/koinos"
      command: --basedir=/koinos
