global:
  amqp: amqp://guest:guest@amqp:5672/
  log-level: info
  instance-id: Koinos

block_producer:
  algorithm: pow
  pow-contract-id: MNF4ikZwygzCshy20gKe1nCMIcmM=

jsonrpc:
  listen: /tcp/8080

p2p:
  peer:
    - /ip4/45.56.104.152/tcp/8888/p2p/Qma3pqGBeUVzUPwn6TE6WWP14arjc5JKVvZac5BpJU1hkr
  checkpoint:
    - 100:zQmdDbpL7tBVrReHJQtvGRtr3gKvKmETYRjzPQMHW3uXC4U
    - 200:zQmRyfc3Crj9isstd52njxRhectbCByTrV6XLARwgPH323x
    - 300:zQmShqpCjhpbFb3uaLYoNgWjL1gaCwycVkcqZPfXZqNmdj4
    - 400:zQmYSbqkmunKBwVvBGMLYvw89sJ2xSxCF4bcQnPkYhWBFkN
    - 500:zQmUgaxM97c7TjE1YKFmua68y7nZwPVNWpgDgJ71BdyxYZc
    - 600:zQmcbYkQVcjy1H8Ki6bVMc9gRx5aGtTf97NXV9qf1VdJynE
    - 700:zQmbornmXaY82wGjFSjX2QxyXAYhHPdcPBtcKGPhBUyX9z5
    - 800:zQmPMhCkrK7VXFEqrJfpu5W7hyEyCxj7h1uupRcBPwqgvai
    - 900:zQmYVG7y9dXC66x4Tuzqj3Ro6e7HKQXvAhKGpnYPTv7i9GS
    - 1000:zQmRBpMRnKzJPdXi9jjeG5GgoXt6qcWBNZDCA49UyCFBmWi
    - 2000:zQmZSNt2Jj2EUMy52vPA1VxDPNjFMQeLE48agqSsM1ogVyY
    - 3000:zQmXTH2hk32yxB7EEPcz5BXBbb2DoAHcVZrRqbZwedpJYB6
    - 4000:zQmd4u514XeDcfu7yyMfF9UYgfwRDLnJcVRMCtTNLQ2BNrB
    - 5000:zQmPAzpGnPYCtZuabU7ymn73jST57VUvSzs8uPojeUEeDqn
    - 6000:zQmQCnaPwkm61KAP4SKwuSG6Qr6b3YCgH9kp3EsLrUaNQvV
    - 7000:zQmWnrzt26NeYa3g6BaKhqt69ZTWHne2281p7sbwPDJc4d8
    - 8000:zQmTjJPZaGGfJUUX8Cx8t8aCwU6qFGePowZT8o2pemBwCLD
    - 9000:zQmVH45MCBcy9rGGYwshqMKJYBJc7hwbfBDGsD7r2sqE7ea
    - 10000:zQmaNyVJ9YaGjYQEpNDYiSab2vsYcULJK6GSqFM6mGcq2XC
    - 11000:zQmWFTTp3wacp4LevAX1NgrxE1WWwsfq66gvyV5royz3A3Q
    - 12000:zQmYHsXmEQ3t1YNpAqLsEZbTkgRcA7NHs18GbuKmZXJ3fsS
    - 13000:zQmUaFpekeyAMfZri3DwbUQpEo1CPtjTNLw71o7ApMD31VU
    - 14000:zQmWRyZtxXQysYrDFJbGcuupFuXgbmc8h9QHz6Mh6BTj8xd
    - 15000:zQmfTSc8ofAQaRnKj1mGvCLUmaMje3sKYnhvG8EAru53Tec
    - 16000:zQmTNXfwJ1bcAQocNBNfBZg6MjsxfzMUk6mmLjCjbboeF8W
    - 17000:zQmeSSHzUxtf5vGWg48ZL5ji2XpHWcnEV3cJ4UVTeCXNCAk
    - 18000:zQmV7JLXUDMUKKCqzgSyxXpSsSWTwtq191HAPKFRny4iNEP
    - 19000:zQmUMSipHWpFBHxx3xoqDChQ3d2XjhgYQzZKh71WU9SkrSV
    - 20000:zQmW615UN4LHQxovHnR8FpfBtE3b87hVr8NgNdALWDyPCPY
    - 21000:zQmXZuvbS8kBmhQWCZMFWU6hDDYcjhsvc8q9L3yRyZWbdU1
    - 22000:zQmPXe5jmCwHRA6h9DifALycQiVGs6CSqSBGRRcReRFfgKb
    - 23000:zQmQgDBq4S5HxJAB6SPhKC9JZcutfEXunMJS9c6NcgYMeHq
    - 24000:zQmTr1HtKJK49ftvk3ZJAsDtSSPcqVatfNVJ7YrhAimtSRp
    - 25000:zQmbQDwRp7T7emmzQ1nc41J8awEn86QGjNfXcjGzPZaazUF
    - 26000:zQmWgyL3h9F5SvKFARgQg8SKouCTbmSwtXUqK8dfq1MLX9G
    - 27000:zQmRgrjaVmNpUoFonkCMYwtSiqN4Whjn3Xd2EAoxRDTnVSC
    - 28000:zQmSFmuHCRAeQg7aWgKFjQGndKqycsrEc7eMLcyEy224Y1y
    - 29000:zQmdgH5H1FpY5nbdxPWb73WjLtCBiHsQjC6h8o3ymz6TxNb
    - 30000:zQmc9gXW4cjbh9yzbknfr3mcKxqa2uP3aXDqYrKTB18et1g
    - 31000:zQmbsZGiWuH4Rz7ZWnAEs6GgGdXPnJmCRvQcMZ4jmu243Vn
    - 32000:zQmZxYxa3ajMabSGxBX9rFWNxadZ85N1jvQf21ncFopVdzz
    - 33000:zQmX7SXFpk7ZxAtuQgwum1ZqiAG9RtyuaBR7oXAh7Nm21Fw
    - 34000:zQmeb5TBzo9wiqJyPBWm7mcvW4oxpbSrRJh28VnAaYNMhQk
    - 35000:zQmXyUUqSHnmSqVao59kc4zViAzW8GKAu2NP1GfCGGS1hRP
    - 36000:zQmTXTfVBHrcxX7t58i9fi2XKpPVBmrMEtj96jmdB1C8dux
    - 37000:zQmZHyuJJK1uRi6wPbTEdScymuYcKuU7uqoak5qJ7U4N26d
    - 38000:zQmfGigcoFPca9HDJvLAiPFtAQVXzS1nZqs3wBTrvwiMubb
    - 39000:zQmXp8QF5CKdzMfmf2Aa3zZYetuC7tnWh6DiGEcNBe1qXvj
    - 40000:zQmRTpKjhpdv6d7WsqoqsyqufFVTWYJqumuxe9Yk7VajJF5
    - 41000:zQmVhaStS1PgQCJ7mPi2AXhDJ4MEX7pr63igZ7FAU1ZbNLY
    - 42000:zQmX8WcefH6rzBD5XwkhnNzhtqCa2zV7bnxXgAP1mdSmL83
    - 43000:zQmRPF5AQc7JaZyvjMAi1oEnzNLyHrvtwsv2hnZDQxouVrv
    - 44000:zQmTtG5V9TAMmvqLGq6eu7EUcdDRhjhcWDzmeoFMBFMceVQ
    - 45000:zQmfBikiZnCMQhJfKNeRvMgnsNXATequ8hEYvugVCwqKFFL
    - 46000:zQmaFvJFsU7aGfVfv8hn7LXMTigHqGJKzmQFe8P2cXYnm6q
    - 47000:zQmXUPKXzypSDNxs5ZxHYhHU1wXvTiQnuo3KjyAnyR2uVvT
    - 48000:zQmRYYmGXCtTTF4bY3zRD4PwENgmr2GbmiaP3AbF47k7fb4
    - 49000:zQmVHiPmz3Grd9CFMgKfCkZ5iiX4ds2o3f9s9aFzq3T9LWg
    - 50000:zQmWGkeasWhWzJ5LfnwE8EfamYZHR744d2Sru5BsroYUGTw
    - 51000:zQmT3sDofAf7Xmo8w9XTEJ42bP7GZkYZbzXexM9xuLuthnq
    - 52000:zQmVLbagy7nh42MtViNGXVQeMprzvuUjKi6pTPweGoqWGWz
    - 53000:zQmNRmygVt7Vn4CPvQKqPDbGFWjNAo72Ts9oFyMoHojnRw2
    - 54000:zQmZAhG2uT9i9yBzii94TPHTPw9nsxFRowJhhzzptRtdxaB
    - 55000:zQmZ8WaTDioGhizmXgJNZ57vV5Mf5ZAbWCBuwZSdmu7WD5r
    - 56000:zQmZJ8BdLFPuH2Uns2E7D2iPrudcrtTc6jjhntr1XFyjSTq
    - 57000:zQmRq39WYFzKs9h1ECErkX8VaXYtr2kYDZvqc6RZNXazt4T
    - 58000:zQmXEU8xnioV79aAKzSYEtZe5hzdATdKh6tGKuGQsTHv4hg
    - 59000:zQmU6koJfSih6oEU2vWQDDr16UotzbjVWKW4ze7yxQtrUKN
    - 60000:zQmU7kfP2iPfDLBCyBz23AYQfvquTwSyotKfJHzdftcQGDL
    - 61000:zQmXvcpjMGuZEGyyostWZP8sbTyw8n1EKPs8VxQ4rHFhDFn
    - 62000:zQmeobPf7HE1fJM3FJAa1ppc5RAijitu3qSAr1LeMBqy7d7
    - 63000:zQmSzt7gRqrCoJxg5NPv5QvSMj2nxcTB1GgVm68eRt4m3S6
    - 64000:zQmZoceENxEJeazzBiyYXCeT7wG3XXLWRh6vRDNJCxu4YAb
    - 65000:zQmNjRQYvjrxDweiDoBG2R89pYgFhXARcSkiQqwwEj7UrkK
    - 66000:zQmVLbxXdUpcnyb531czjkJvF5soJ1ZUX6hRU6DaoJd3xu9
    - 67000:zQmatCkZd6Dwhc19bMqwL6AF4Sc6KfumZhgXitWMxYzpaZQ
    - 68000:zQmQn1oSGLh7S9MM4ZDVrA3xYgwSbU6w6cjsiwkNn8yHxse
    - 69000:zQmQitE2iFH4pmRmG6d8tby1WNRR1H8LvVLBhCZZKBxnpgB
    - 70000:zQmbHtvtpkuaeWNy7pcWMtboLBjfXVxpGBEJwjrGoXNYHPi
    - 71000:zQmRmkaaxxxKD3LwRZszHPoHzMz6HZLXnVsR3iRQFHEh73r
    - 72000:zQmf5bQWRCqvin8oJ2126XrhrAXvSKsVanJ8SdVWPEfxq8f
    - 73000:zQmTgab774r5gVzXd7bxJM6RVGqaDsn2XHQz4b7txLAeY2j
    - 74000:zQmUfJEV4qwxjD6HbbqGqujHH168CSdGc9zPmagXvYKXMTr
    - 75000:zQmYMmRxV8Zi6MecU8mAVmQxt5KDhzEoBfmL4aM5StvaCuz
    - 76000:zQmW8HvLPnteBfAftAsaaA6vfmPYujTzYGnZmzw5Wakk1bt
    - 77000:zQmbXTazFgkmqZFzcugEhq6Tzj2wwas774EGw6zmd7FhMrM
    - 78000:zQmXuhzS9JbXhtsr5YdhNzofCvUC7NcY3D3ZgwtnRyGP7HY
    - 79000:zQmYAcXGan2JNL2QdWvRSXA6MbYoi9HcMfFBENpwGgzCnva
    - 80000:zQmQ5y99boycKXmepUCCtVWxurxchmYuEbTXBawCHyhiobS
    - 81000:zQmaCae5aUqdzzMoJ43BVUdA6WVytWRkjpv9n3iSawjsDUG
    - 82000:zQmTcSPJ8E6ZtbxMDAZYDKzinVTsR8tynNxpveATUXddK2k
    - 83000:zQmNoPw5uuzsMheg8aUa7TUJhDKEZkLnv4FKahCMHj5hvzn
    - 84000:zQmXwbzeYSCaiBrFDwGV78Kw29dyzTq7MKF9yA6hgnrKP4h
    - 85000:zQmV29egfRqSDFoB79JFzZwuJcJvwNt2FMnxip4xJU27to5
    - 86000:zQmWvCgWyazQmfSkNykD3AyyhjFU7jqVzMABccr3kHoaEJo
    - 87000:zQmeF3BfPDwGEuueDixfD7qD8DNvMv2nD41Sp7kuCqeYpDq
    - 88000:zQmTu2X7Hhsm42Gp6hMGG3d8ggezrk2XfWUFi5MF3uzaq37
    - 89000:zQmTWpZ2W3rcZsqddCZ93LYHLNMCR9RYiqERUoUGzJxrQB5
    - 90000:zQmNQbrfsRVapWJ5p1JZBm4bPZjHxVc3XG6sDtCmYT5XLng
    - 91000:zQmd2Bte2XCWRGqLRB1aXLh8dmcaHWqsPkJPGAD4mjcSLVh
    - 92000:zQmYfwujFS2QUKx17iSn21Mevis2XT9sVEuFx4udaTvXASF
    - 93000:zQmfWZovA4z78SXQGj5za9E5hsYJfiE7EPYbSURUa7pUyiT
    - 94000:zQmRMj2VVEc6eAj17N5PskyRbpERGAsHTxG3iaSxVB4ALf4
    - 95000:zQmahSqq8YWzHZx5caQXbHG99FEB9L5iXGsf81jSfg5WEVL
    - 96000:zQmdrK51Lvr8ZcmKd9q7yj4G59ft2bmTtNJDpJ5wneez7Sx
    - 97000:zQmZEdjKx5Ax1keNo4UTk3CNvw3kHQk8DQWuUd7gWVuEFUV
    - 98000:zQmSWZPPo8JYGGtrVrc3vBroEfiWun26i5sGH1ZRkTEk1Q1
    - 99000:zQmXEgcmrybvqKiH3QaGBzLdQpNZgvgMm9rd9D37ESLg1ub
    - 100000:zQmW1XcTmewXGNpbGZeDPWXmNkUGodb5rsm9f4FKQ2vSLUN
    - 101000:zQmQUbfbqDLJwU5F5TNFN2tfRLR61r8HdkPVTpT1zmwo6vp
    - 102000:zQmTmb7mh6c8gZv6MruusChm8F2t3g7hitCRodiGxXNw6hL
    - 103000:zQmQ8LCVWTPuAVVjQaGiaFChq5D24WmnBjPJvYMC3tvHWUC
    - 104000:zQmSf5TTeAKJTuyaTy3jrGKZjhe5pXeKBFF3NhsFHC24d9R
    - 105000:zQmVhwaxc4L7keSdCKRynai2BCGTKZ71TncBMkEn1JfEVmX
    - 106000:zQmdNTuLN79hWSTvMaeYEnZ9zThSWNAMYhnkLPKQognrty4
    - 107000:zQmYxN7VoVQqoCK91nxK6AhkVbzJ75mVWiRPvFN7GeGwCdT
    - 108000:zQmS8UCn8pVF1hHKULJVUaJDsPK7qCaVezYaPBCC4wusATH
    - 109000:zQmUKnPNaa9EPNUqemq8UU9EQbcayiZChf41ahRK1z3i5QR
    - 110000:zQmPiZkfD9RU9mNRWwwXsmPu5TSti2vk472V9j9265k3YTY
    - 111000:zQmW2RsDWmC5BNnNbcmuXwiEHZKzc8GB9MfVMJEvf4h3KC4
    - 112000:zQmeB522mQHPntXLc29FTC6z5NyGxa6yPv1V44d62TtKeeH
    - 113000:zQmQhBbp1o5D31zWV7GsEXzjRrcQLcc4AjpQBJ52LsTVjyc
    - 114000:zQmQKz9WasP9Wzju61YY6nmGK98rLYfkxraV3j2T2SHoSmf
    - 115000:zQmchhSWousRH8yC1vf8oV6sepVJEjvE498hcZpEkeeyKNF
    - 116000:zQmbtFkhp7FzARTA5Non8apisAaZMy38o1t8oWGQWQG5u5k
    - 117000:zQmQHRLhDfcGsQNbefsYrmR4yoqM9aMuk6RHR282iKmNYyC
    - 118000:zQmXVHtYkHYsTJUVSRBNaJVTgjJVMY5zzcFXPs93t18MGoK
    - 119000:zQmPZzaTRSHe9XVoWBQe6mXvTP3YqfBcedrnW5Ly5mDnsCd
    - 120000:zQmaYSty8GWmtiHs6EX8hAAgLwEtmsxLqFuFZfc9C7vvhxj
    - 121000:zQmcxXnfaTYCHCGpcypmeaSRTGGmh8PzNoTDbri7BB8jVY1
    - 122000:zQmTVGbD1daRRC7bXfm3WnLuGgMCHeqvxzDU2ErAmqFory1
    - 123000:zQmdsELRP2hprAW2eTCq3cZXPpjCUSnp46Sgi7kondEgDGm
    - 124000:zQmYGgmyNPdVB2kr3PrDPsepvfdW8X27zmWufw6y5SEW3eV
    - 125000:zQmfP2YV8ptt5B3dcB6wNbH39VwMmvHXdjcWCvEAkdqEUDE
