global:
  amqp: amqp://guest:guest@amqp:5672/
  log-level: info
  instance-id: Koinos

block_producer:
  algorithm: pow
  pow-contract-id: MNF4ikZwygzCshy20gKe1nCMIcmM=

jsonrpc:
  listen: /tcp/8080

p2p:
  peer:
    - /ip4/45.56.104.152/tcp/8888/p2p/Qma3pqGBeUVzUPwn6TE6WWP14arjc5JKVvZac5BpJU1hkr
